# Generated by Django 4.0.4 on 2022-05-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_note_author_alter_note_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(null=True, upload_to='upload_image/'),
        ),
    ]
